### ISSUE TITLE
Building with mingw: os.c build failure

### ISSUE THREAD

**Issue by vanaur** [microsoft/mimalloc#217] opened 2020-04-02 14:12 UTC
Maybe my question doesn't belong in an issue, in which case I really apologize.

I would like to build the mimalloc library on Windows, without Visual Studio. I use GCC and Make to build my projects.

I have configured the CMake (where I so specified the compilers to use) to compile according to these preferences and it seems to work fine.

However, I have a compilation problem when building `os.c`, as shown in the given picture, `PROCESSOR_NUMBER` (and the functions that follow) don't seem to be found or exist. Nevertheless, some fixes to the MinGW version [seem to have already been made](https://github.com/microsoft/mimalloc/issues/25) 🤔

![img](https://user-images.githubusercontent.com/28791317/78258013-e8868f00-74fa-11ea-87bc-acdb9c0ff5de.PNG)

I'm not used to using Windows headers, and I haven't found anything on the Internet that can help me overcome this problem of build. I don't know where to find what is missing. What should I change in my configurations? Or don't I have all the necessary files?

I would really like to test mimalloc, which looks really well designed, thanks :)

**Comment by daanx** [comment] 2020-04-02 14:34
Ah interesting. I would like mingw compilation to work. 
Can you try to change the `#ifdef WIN32` on line 1015 to `#ifdef MAXIMUM_PROCESSORS` and see if that compiles? 
If not, change it to `#if defined(WIN32) && !defined(__MINGW32__)` and try that. 
Both these options will disable NUMA awareness though -- not great :-(

A better option is to make the needed definitions available. Perhaps you need to include `<processthreadsapi.h>` explicitly? 
Or as a final option declare them inline in `os.c` for mingw compilation? something like:
```
typedef struct _PROCESSOR_NUMBER {
    WORD   Group;
    BYTE  Number;
    BYTE  Reserved;
} PROCESSOR_NUMBER, *PPROCESSOR_NUMBER;
WINBASEAPI VOID WINAPI
GetCurrentProcessorNumberEx(    _Out_ PPROCESSOR_NUMBER ProcNumber );
WINBASEAPI BOOL WINAPI
GetNumaProcessorNodeEx( _In_  PPROCESSOR_NUMBER Processor, _Out_ PUSHORT NodeNumber );
```

Let me know how it goes.

**Comment by vanaur** [comment] 2020-04-02 16:16
Thank you for your response,
I tried your proposals in the `dev` branch, and this is the result:

1) The same error occurs when replace `#ifdef WIN32` by `#ifdef MAXIMUM_PROCESSORS`.

2) `#if defined(WIN32) && !defined(__MINGW32__)`, seems to compile correctly, but I'm getting errors in the linker, as shown in the following picture:

![img2](https://user-images.githubusercontent.com/28791317/78272194-7f5c4700-750d-11ea-867f-9fc7550df501.PNG)

Which seems strange because I get the expected generated files:

![img3](https://user-images.githubusercontent.com/28791317/78272211-84b99180-750d-11ea-92cc-6339af570e27.PNG)

and the test executable also well works.

3) For the explicit file inclusion `<processthreadsapi.h>`, no change from the original problem is to be reported.

4) Finally, the last proposed option:
```c
#ifdef __MINGW32__
typedef struct _PROCESSOR_NUMBER {
    WORD   Group;
    BYTE  Number;
    BYTE  Reserved;
} PROCESSOR_NUMBER, *PPROCESSOR_NUMBER;
WINBASEAPI VOID WINAPI
GetCurrentProcessorNumberEx(    _Out_ PPROCESSOR_NUMBER ProcNumber );
WINBASEAPI BOOL WINAPI
GetNumaProcessorNodeEx( _In_  PPROCESSOR_NUMBER Processor, _Out_ PUSHORT NodeNumber );
```
also works and generate the files, but still with the linker errors display, as shown in the first image.

**Comment by daanx** [comment] 2020-04-02 16:24
I see. That the explicit inclusion of the definitions works is good since we can use that to have numa aware allocation from mingw too. 

The linker errors seem unrelated to this particular issue -- the linker cannot find `mi_free` which means the linker didn't get the right library to link with? Perhaps run cmake as verbose to see how it links. Perhaps there is some unix .so versus .dll (or .a versus .lib) confusion in the cmake file?

**Comment by vanaur** [comment] 2020-04-02 16:56
This is what the `CMAKE_VERBOSE_MAKEFILE ON` option displays: [https://pastebin.com/DuPAtvN9](https://pastebin.com/DuPAtvN9)

I don't know if this is what you were expecting?

Anyway, the linker error occurs when linking "`mimalloc-test-stress.exe`":
`[100%] Linking C executable mimalloc-test-stress.exe`

This file does not appear in the well generated ones. I don't know if it's maybe a linker error for this particular file.

**Comment by daanx** [comment] 2020-04-02 17:06
Ah, I meant to say that I would like to see the actual linker command line. I can get that by running 
```
make VERBOSE=1
```
The link command I see on Ubuntu for `mimalloc-test-stress` is:
```
[ 96%] Linking C executable mimalloc-test-stress
/usr/bin/cmake -E cmake_link_script CMakeFiles/mimalloc-test-stress.dir/link.txt --verbose=1
/usr/bin/cc  -g   CMakeFiles/mimalloc-test-stress.dir/test/test-stress.c.o  -o mimalloc-test-stress -rdynamic libmimalloc-debug.so.1.6 -lpthread -lrt -Wl,-rpath,/xxx/dev/mimalloc/out/debug
make[2]: Leaving directory '/mnt/c/Users/daan/dev/mimalloc/out/debug'
```

**Comment by vanaur** [comment] 2020-04-02 17:20
Ah ok, excuse me. Here's what I get (I've removed the Warnings to make it easier to read):
```
Linking C executable mimalloc-test-stress.exe
"...\cmake.exe" -E cmake_link_script CMakeFiles\mimalloc-test-stress.dir\link.txt --verbose=1
"...\cmake.exe" -E remove -f CMakeFiles\mimalloc-test-stress.dir/objects.a
C:\Strawberry\c\bin\ar.exe cr CMakeFiles\mimalloc-test-stress.dir/objects.a @CMakeFiles\mimalloc-test-stress.dir\objects1.rsp
C:\Strawberry\c\bin\gcc.exe -O3 -DNDEBUG   -Wl,--whole-archive CMakeFiles\mimalloc-test-stress.dir/objects.a -Wl,--no-whole-archive  -o mimalloc-test-stress.exe -Wl,--out-implib,libmimalloc-test-stress.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\mimalloc-test-stress.dir\linklibs.rsp
```

**Comment by daanx** [comment] 2020-04-02 18:14
Hmm, looks ok at first look. I wonder if it has to do with the "implib"?  Maybe static linking works? Not sure why it fails as I haven't used mingw for a while. Perhaps there is a mingw expert that can pitch in?

**Comment by vanaur** [comment] 2020-04-02 22:58
That may indeed be the case. I did a little research, it seems that implib doesn't work for mingw-w64, but only for w32 if I understood correctly ([source](https://forum.dlang.org/thread/abvlnpiydrwuhjniqwil@forum.dlang.org)).
Maybe compiling with a w32 version of the mingw toolchain should solve this problem. I don't have that version, but if I have time tomorrow, I'll try.

**Comment by jonty-dawson** [comment] 2020-04-06 16:11
I bumped into this. For the mimalloc-test-stress link error, is it missing __declspec(dllexport) expected for Windows in [mimalloc.h#L55-L57](https://github.com/microsoft/mimalloc/blob/82684042be1be44d34caecc915fb51755278d843/include/mimalloc.h#L55-L57) ?

Seems fixed by defining mi_decl_export the same as in the _MSC_VER condition above.
```
#elif defined(__GNUC__)                 // includes clang and icc
  #if !defined(__MINGW32__)
    #define mi_cdecl                      // leads to warnings... __attribute__((cdecl))
    #define mi_decl_export                __attribute__((visibility("default")))
  #else
    #define mi_cdecl                      __cdecl
    #if !defined(MI_SHARED_LIB)
      #define mi_decl_export
    #elif defined(MI_SHARED_LIB_EXPORT)
      #define mi_decl_export              __declspec(dllexport)
    #else
      #define mi_decl_export              __declspec(dllimport)
    #endif
  #endif
```

**Comment by jonty-dawson** [comment] 2020-04-06 16:29
For the PROCESSOR_NUMBER compile error in os.c, it looks like mingw defaults to an old _WIN32_WINNT version. Setting to >= _WIN32_WINNT_WIN7 seems to fix without need to modify code. 

Mingw also seems to have an old winnt.h which is missing MEM_EXTENDED_PARAMETER_TYPE_BITS and associated types, causing [-Wunused-parameter] for 'numa_node' in [mi_os_alloc_huge_os_pagesx](https://github.com/microsoft/mimalloc/blob/dev/src/os.c#L827). It may be viable to add these missing defines / declarations after include <windows.h>, similar to [here](https://hg.mozilla.org/releases/mozilla-release/rev/7a4a079c4db08f6df0f205ccc8ace4584ed03ca6)?

I also got printf format warnings for "%z", specifying ```__USE_MINGW_ANSI_STDIO=1``` seems to work around.

With the above, building without warning on win 10 pro / mingw-w64 / gcc 8.1.0:
```
mkdir -p build_mingw_gcc/release && cd build_mingw_gcc/release
cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-D_WIN32_WINNT=_WIN32_WINNT_WIN7 -D__USE_MINGW_ANSI_STDIO=1" ../..
cmake --build . -j -v
ctest
```

**Comment by daanx** [comment] 2020-04-06 16:56
@jonty-dawson : Awesome ! I just pushed a fix for the dynamic compilation by just using the same path as `_MSC_VER` for `__MINGW32__` -- this way we do not need to duplicate the code for export declarations. (commit #50bfacd).  The other commit to avoid the numa warning seems just too much to include all the definitions and the warning is fixed already by #64e8cfa.  (Just means huge pages and numa awareness is not working on mingw until they update the headers.)

Can you try the latest `dev` branch to see if works now?

**Comment by jonty-dawson** [comment] 2020-04-06 17:30
Hi @dannx, with https://github.com/microsoft/mimalloc/tree/50bfacdb71503181e58a2e3ca3f1db14eb390632 I'm getting a bunch of 'restrict' attribute warnings.

I guess you still want the empty [#define mi_decl_restrict](https://github.com/microsoft/mimalloc/blob/50bfacdb71503181e58a2e3ca3f1db14eb390632/include/mimalloc.h#L58) and others from the ```elif defined(__GNUC__)``` condition branch, but agree you might be able to DRY with some re-arranging.
First occurrence:
```
./src/stats.c:7:
./include/mimalloc.h:98:1: warning: 'restrict' attribute directive ignored [-Wattributes]
 mi_decl_nodiscard mi_decl_export mi_decl_restrict void* mi_malloc(size_t size)  mi_attr_noexcept mi_attr_malloc mi_attr_alloc_size(1);
 ^~~~~~~~~~~~~~~~~
```

**Comment by daanx** [comment] 2020-04-06 17:57
Just pushed more fixes -- can you try again?  Hope it goes through this time around :-)

**Comment by jonty-dawson** [comment] 2020-04-06 18:02
0f3bd05fd5a9471ddb9f7fe42b40a561b7e3650b causes error if I build with -D_WIN32_WINNT=_WIN32_WINNT_WIN7
```
src\os.c:1021:16: error: redefinition of 'struct _PROCESSOR_NUMBER'
```
No compile error if I build with mingw's default old _WIN32_WINNT, but get reintroduced [-Wimplicit-function-declaration] for FlsAlloc.

**Comment by jonty-dawson** [comment] 2020-04-06 18:12
0a3e5bb69980f29373337e564a80d77de1b80af0 fixes the `restrict` warnings on mingw 👍

**Comment by daanx** [comment] 2020-04-06 18:27
Just pushed commit 34d3b8c, one more try :-)  Now I check the `_WIN32_WINNT` version to conditionally include the definitions for GetProcessor and FlsAlloc.

**Comment by jonty-dawson** [comment] 2020-04-06 19:10
That seems good - confirmed can build on mingw64 without additional compile switches, and also with any of `-D_WIN32_WINNT=_WIN32_WINNT_WIN7` / `-D_WIN32_WINNT=_WIN32_WINNT_WIN8` /  `-D_WIN32_WINNT=_WIN32_WINNT_WIN10` 

Thanks!

**Comment by daanx** [comment] 2020-04-06 19:11
Great! Thanks for your help in fixing this issue.

**Comment by dannx** [comment] 2020-04-06 19:12
Sorry sir, but you have the wrong email address.

**Comment by jonty-dawson** [comment] 2020-04-06 19:22
sorry my bad, I meant daanx not dannx

**Closed** 2020-04-15 18:33 UTC
Labels: help wanted
