### ISSUE TITLE
Conda support

### ISSUE THREAD

**Issue by elbaro** [microsoft/mimalloc#219] opened 2020-04-03 07:27 UTC
mimalloc fails to build with conda gcc-7 or clang.

```
-- Install directory: /usr/local/lib/mimalloc-1.6
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: $SRC_DIR/out/release
+ make
Scanning dependencies of target mimalloc-static
[  3%] Building C object CMakeFiles/mimalloc-static.dir/src/stats.c.o
[  6%] Building C object CMakeFiles/mimalloc-static.dir/src/random.c.o
[  9%] Building C object CMakeFiles/mimalloc-static.dir/src/os.c.o
[ 12%] Building C object CMakeFiles/mimalloc-static.dir/src/arena.c.o
[ 15%] Building C object CMakeFiles/mimalloc-static.dir/src/region.c.o
[ 18%] Building C object CMakeFiles/mimalloc-static.dir/src/segment.c.o
[ 21%] Building C object CMakeFiles/mimalloc-static.dir/src/page.c.o
[ 24%] Building C object CMakeFiles/mimalloc-static.dir/src/alloc.c.o
In file included from /home/conda/staged-recipes/build_artifacts/mimalloc_1585827425893/work/src/alloc.c:15:
/home/conda/staged-recipes/build_artifacts/mimalloc_1585827425893/work/src/alloc-override.c:176:7: error: redefinition of 'aligned_alloc'
void* aligned_alloc(size_t alignment, size_t size)          { return mi_aligned_alloc(alignment, size); }
      ^
/home/conda/staged-recipes/build_artifacts/mimalloc_1585827425893/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/stdlib.h:513:21: note: previous definition is here
static inline void* aligned_alloc (size_t al, size_t sz)
                    ^
1 error generated.
make[2]: *** [CMakeFiles/mimalloc-static.dir/src/alloc.c.o] Error 1
make[1]: *** [CMakeFiles/mimalloc-static.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by daanx** [comment] 2020-04-06 15:55
I see. That is troublesome -- it seems that glibc defines `aligned_alloc` as an inline definition so we cannot override it in the usual way :-( Wish they would have defined it as a regular entry. We are not the first to encounter this it seems: <https://github.com/conda/conda-build/issues/3165>.

They seem to fix it by undefining `_GNU_SOURCE` ?  Can you try if this works. Go to `src/alloc.c` (as `alloc-override.c` is included there) and add `#undef _GNU_SOURCE` as the first line ( -- at least before including `<stdlib.h>`). Maybe that will work?

Btw. as a workaround, you can just comment out the mimalloc `aligned_alloc` declaration but it would be nice if we get it to work unchanged on Conda as well.

**Comment by elbaro** [comment] 2020-04-13 10:46
`#undef _GNU_SOURCE` didn't work. commenting `aligned_alloc` out worked. Is there any disadvantage of not using mimalloc's version of `aligned_alloc`?

**Comment by daanx** [comment] 2020-04-15 18:57
@elbaro: I pushed a possible fix for this -- can you try it out? Thanks.

**Comment by elbaro** [comment] 2020-04-16 08:02
```
❯ $CXX -dM -E test.cc | rg ALIGN 
#define _GLIBCXX_HAVE_STDALIGN_H 1
#define _GLIBCXX_HAVE_MEMALIGN 1
#define _GLIBCXX_HAVE_POSIX_MEMALIGN 1
#define __BIGGEST_ALIGNMENT__ 16
#define _GLIBCXX_HAVE_ALIGNED_ALLOC 1
```

On my machine `_GLIBCXX_HAVE__ALIGNED_MALLOC` is not defined.

```
❯ $CXX --version
x86_64-conda_cos6-linux-gnu-c++ (crosstool-NG 1.23.0.449-a04d0) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by daanx** [comment] 2020-04-20 16:28
Ah, it is tricky. I think I got the #ifdefs correct now; can you try once more with `dev`?

**Comment by elbaro** [comment] 2020-04-21 05:47
77acf5a and dev (e31298b) worked.

**Closed** 2020-04-21 16:57 UTC

**Comment by asl** [comment] 2021-02-04 18:26
Actually, the problem is conda's private glibc patch which is broken in many ways. So, the problem should really be fixed on conda's side :)
