### ISSUE TITLE
2.1.4: build fail on centos7

### ISSUE THREAD

**Issue by jimying** [microsoft/mimalloc#885] opened 2024-04-25 06:06 UTC
I try use clang17 and gcc9 build mimalloc on centos7 x86_64, same error log:
```
In file included from /usr/include/string.h:633,
                 from /home/build/mimalloc-2.1.4/include/mimalloc/internal.h:291,
                 from /home/build/mimalloc-2.1.4/src/alloc.c:12:
/home/build/mimalloc-2.1.4/src/alloc-override.c:139:24: error: expected identifier or ‘(’ before ‘__extension__’
  139 |   mi_decl_export char* strdup(const char* str)             MI_FORWARD1(mi_strdup, str)
```

**Comment by hombit** [comment] 2024-04-25 13:40
I have the same issue with [Python's manylinux2014 images](https://github.com/pypa/manylinux), which are Centos7.

The issue can be reproduced with this Dockerfile:

```Dockerfile
FROM quay.io/pypa/manylinux2014_x86_64

RUN curl -LOJ https://github.com/microsoft/mimalloc/archive/refs/tags/v2.1.4.tar.gz \
    && tar -xzf mimalloc-2.1.4.tar.gz \
    && rm mimalloc-2.1.4.tar.gz

WORKDIR /mimalloc-2.1.4
RUN mkdir -p out/release \
    && cd out/release \
    && cmake ../..

WORKDIR /mimalloc-2.1.4/out/release
CMD ["make"]
```

```sh
docker build --tag manylinux-mimalloc .
docker run --rm manylinux-mimalloc
```

Please also see the relevant discussion in this `mimalloc_rust` issue:
https://github.com/purpleprotocol/mimalloc_rust/issues/111

**Comment by daanx** [comment] 2024-04-28 02:51
Thanks for the repro steps -- I hope to get this resolved soon.

**Comment by keyihao** [comment] 2024-05-09 07:32
Same issue with gcc 9 and gcc 11 on CentOS7

**Comment by tbzhang** [comment] 2024-05-10 12:42
This seems to be incompatible with older glibc version, because of an unexpected macro expansion coming from [bits/string2.h](https://sites.uclouvain.be/SystInfo/usr/include/bits/string2.h.html) :
```
# ifndef _HAVE_STRING_ARCH_strdup

extern char *__strdup (const char *__string) __THROW __attribute_malloc__;
#  define __strdup(s) \
  (__extension__ (__builtin_constant_p (s) && __string2_1bptr_p (s)           \
                  ? (((const char *) (s))[0] == '\0'                          \
                     ? (char *) calloc ((size_t) 1, (size_t) 1)               \
                     : ({ size_t __len = strlen (s) + 1;                      \
                          char *__retval = (char *) malloc (__len);           \
                          if (__retval != NULL)                               \
                            __retval = (char *) memcpy (__retval, s, __len);  \
                          __retval; }))                                       \
                  : __strdup (s)))

#  if defined __USE_SVID || defined __USE_BSD || defined __USE_XOPEN_EXTENDED
#   define strdup(s) __strdup (s)
#  endif
# endif
```

**Comment by nautaa** [comment] 2024-05-10 13:10
This may be due to `strdup` being a preprocessor macro.
 if it's ok, I'll submit a PR to fix this? ref: https://stackoverflow.com/questions/51233563/is-it-possible-to-overwrite-strdup-from-string-h-with-my-own

**Comment by hombit** [comment] 2024-05-21 12:16
I believe it is fixed by the latest release

**Closed as completed** 2024-05-21 12:20 UTC
